CREATE DATABASE PUBLICSAFETY;

USE PUBLICSAFETY;

CREATE TABLE ZONE (
ZONE_ID INT PRIMARY KEY,
ZONE_NAME VARCHAR(50) DEFAULT NULL,
SQUAD_NUMBER INT,
ZONE_VERTICES INT,
ZONE_AREA POLYGON NOT NULL SRID 0,SPATIAL INDEX(ZONE_AREA)
) ENGINE=MyISAM;

CREATE TABLE OFFICER (
BADGE_NUMBER INT PRIMARY KEY,
OFFICER_NAME VARCHAR(20) DEFAULT NULL,
SQUAD_NUMBER INT,
OFFICER_LOCATION POINT NOT NULL SRID 0,SPATIAL INDEX(OFFICER_LOCATION)
) ENGINE=MyISAM;

CREATE TABLE ROUTE (
ROUTE_NUMBER INT PRIMARY KEY,
ROUTE_VERTICES INT,
ROUTE_LINE LINESTRING NOT NULL SRID 0,SPATIAL INDEX(ROUTE_LINE)
) ENGINE=MyISAM;

CREATE TABLE INCIDENT (
INCIDENT_ID INT PRIMARY KEY,
INCIDENT_TYPE VARCHAR(50) DEFAULT NULL,
INCIDENT_LOCATION POINT NOT NULL SRID 0,SPATIAL INDEX(INCIDENT_LOCATION)
) ENGINE=MyISAM;